# Generated by Django 5.1.7 on 2025-06-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kh', models.CharField(editable=False, max_length=10, unique=True)),
                ('ten_kh', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mat_khau', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('ma_loai', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Mã loại')),
                ('ten_loai', models.CharField(max_length=100, verbose_name='Tên loại')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sp', models.CharField(blank=True, max_length=20, unique=True)),
                ('ten_san_pham', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('ten_loai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên loại')),
                ('mo_ta', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng trong kho')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Hình ảnh')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('ma_tk', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tenTK', models.CharField(max_length=30)),
                ('matKhau', models.CharField(max_length=50)),
                ('hoTen', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('ma_dh', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ngay_dat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantri.khachhang', verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quantri.donhang', verbose_name='Đơn hàng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantri.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
    ]
