# Generated by Django 5.1.6 on 2025-06-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='tai_khoan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantri.taikhoan'),
        ),
    ]
