# Generated by Django 5.1 on 2025-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0003_taikhoan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='phuong_thuc',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
