# Generated by Django 5.1 on 2025-06-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0004_donhang_phuong_thuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='phuong_thuc',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản ngân hàng')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
