# Generated by Django 5.1 on 2025-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0005_alter_donhang_phuong_thuc'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='tong_tien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền'),
        ),
    ]
