# Generated by Django 5.1.7 on 2025-06-07 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0006_donhang_tong_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('dang_giao', 'Đang giao'), ('da_giao', 'Đã giao')], default='dang_giao', max_length=20),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantri.khachhang'),
        ),
    ]
