# Generated by Django 5.1.7 on 2025-06-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0007_donhang_trang_thai_alter_donhang_khach_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_giao', 'Đang giao'), ('da_giao', 'Đã giao')], default='cho_xu_ly', max_length=20),
        ),
    ]
