# Generated by Django 5.1.7 on 2025-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0008_alter_donhang_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_giao', 'Đang giao'), ('da_giao', 'Đã giao'), ('da_bi_xoa', 'Đã bị xóa')], default='cho_xu_ly', max_length=20),
        ),
    ]
