# Generated by Django 5.1 on 2025-06-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ma_kh',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
